### ISSUE TITLE
There is print_r inside fetchImage

### ISSUE THREAD

**Issue by ArthurRM** [sirv/sirv-rest-api-php#1]
There is a `print_r` inside `fetchImage` basically making the function unusable in production.

In general what is the status of this client? I also noticed that using `wait` flag with `fetchImage` doesn't actually fully wait for the image to become ready. I need to wait another couple of seconds before the dynamic imaging url's return a non-415 response.

**Comment by jacket** [comment]
Thanks for reporting this @ArthurRM! The issue has been resolved. Can you try again please?

We are keen to improve the client and are driven by requests, so please do share any requests that you have.

**Comment by ArthurRM** [comment]
Hi, it is resolved.

Thanks!
